import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 * ButtonPanel is one of two main components of TextStreamGUI.  It consists of a main JButton that
 * when clicked, inquires of the other modules to get their state (the "selections" made by the user)
 * and puts that data in a StringBuffer which can be read by the TextGUI InputStream.
 * <p>
 * In addition, it may contain modules of other types of GUI components which allow selections to be made
 * by the user.
 */
public class ButtonPanel {
    private JPanel mainPanel;
    private JButton mainButton;
    private ArrayList<AbstractButton> buttons;
    private ButtonModule buttonModule;
    private JPanel buttonModulePanel;
    private JLabel label;
    StringBuffer input;

    /**
     * @param input - the StringBuffer from the main TextStreamGUI that the InputStream reads out of.
     *              ButtonPanel will append information into this StringBuffer to make it available
     *              to the InputStream
     */
    public ButtonPanel(StringBuffer input) {
        this.input = input;
        buttonModule = new SingleSelectOptionModule("Selection");
        CellConstraints cc = new CellConstraints();
        buttonModulePanel.setLayout(new FormLayout("fill:d:noGrow", "center:max(d;4px):noGrow"));
        buttonModulePanel.add(buttonModule.getRootPanel(), cc.xy(1, 1));
        mainButton.addActionListener(new ActionListener() {
            /**
             * @param e ActionEvent that triggered the call of this method
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                input.append(buttonModule.getSelectionText());
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:179px:noGrow", "center:377px:grow,top:4dlu:noGrow,center:d:grow"));
        mainPanel.setPreferredSize(new Dimension(200, 600));
        mainButton = new JButton();
        mainButton.setPreferredSize(new Dimension(78, 50));
        mainButton.setText("Submit");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(mainButton, new CellConstraints(1, 3, 1, 1, CellConstraints.DEFAULT, CellConstraints.BOTTOM, new Insets(0, 5, 0, 5)));
        buttonModulePanel = new JPanel();
        buttonModulePanel.setLayout(new FormLayout("", ""));
        buttonModulePanel.setPreferredSize(new Dimension(200, 380));
        mainPanel.add(buttonModulePanel, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.TOP));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public JPanel getRootPanel() {
        return mainPanel;
    }

    public void setButtonModule(ButtonModule buttonModule)
    {
        buttonModulePanel.remove(0);
        CellConstraints cc = new CellConstraints();
        buttonModulePanel.add(buttonModule.getRootPanel(), cc.xy(1, 1));
        this.buttonModule = buttonModule;
    }

    public ButtonModule getButtonModule()
    {
        return buttonModule;
    }
}
