import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 * ButtonPanel is one of two main components of TextStreamGUI.  It consists of a main JButton that
 * when clicked, inquires of the other modules to get their state (the "selections" made by the user)
 * and puts that data in a StringBuffer which can be read by the TextGUI InputStream.
 * <p>
 * In addition, it may contain modules of other types of GUI components which allow selections to be made
 * by the user.
 */
public class ButtonPanel {
    private JPanel mainPanel;
    private JButton mainButton;
    private JRadioButton aRadioButton;
    private JRadioButton bRadioButton;
    private JRadioButton cRadioButton;
    private JRadioButton dRadioButton;
    private JRadioButton eRadioButton;
    private ArrayList<AbstractButton> buttons;
    private JPanel buttonPanelModule;
    private JLabel label;
    StringBuffer input;

    /**
     * @param input - the StringBuffer from the main TextStreamGUI that the InputStream reads out of.
     *              ButtonPanel will append information into this StringBuffer to make it available
     *              to the InputStream
     */
    public ButtonPanel(StringBuffer input) {
        this.input = input;
        this.buttons = new ArrayList<AbstractButton>();
        this.buttons.add(aRadioButton);
        this.buttons.add(bRadioButton);
        this.buttons.add(cRadioButton);
        this.buttons.add(dRadioButton);
        this.buttons.add(eRadioButton);

        mainButton.addActionListener(new ActionListener() {
            /**
             * @param e ActionEvent that triggered the call of this method
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                for (AbstractButton b : buttons)
                    if (b.isSelected()) {
                        input.append(b.getText());
                        input.append("\n");
                    }
/*                if (bRadioButton.isSelected()) {
                    input.append(bRadioButton.getText());
                    input.append("\n");
                }
                if (cRadioButton.isSelected()) {
                    input.append(cRadioButton.getText());
                    input.append("\n");
                }
                if (dRadioButton.isSelected()) {
                    input.append(dRadioButton.getText());
                    input.append("\n");
                }
                if (eRadioButton.isSelected()) {
                    input.append(eRadioButton.getText());
                    input.append("\n");
                }*/
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:179px:noGrow", "center:377px:grow,top:4dlu:noGrow,center:d:grow"));
        mainPanel.setPreferredSize(new Dimension(200, 600));
        mainButton = new JButton();
        mainButton.setPreferredSize(new Dimension(78, 50));
        mainButton.setText("Submit");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(mainButton, new CellConstraints(1, 3, 1, 1, CellConstraints.DEFAULT, CellConstraints.BOTTOM, new Insets(0, 5, 0, 5)));
        buttonPanelModule = new JPanel();
        buttonPanelModule.setLayout(new FormLayout("fill:d:noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        buttonPanelModule.setPreferredSize(new Dimension(200, 380));
        mainPanel.add(buttonPanelModule, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.TOP));
        label = new JLabel();
        label.setAutoscrolls(true);
        label.setPreferredSize(new Dimension(200, 25));
        label.setText("Selection");
        buttonPanelModule.add(label, new CellConstraints(1, 1, 1, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(5, 5, 5, 5)));
        aRadioButton = new JRadioButton();
        aRadioButton.setText("A");
        buttonPanelModule.add(aRadioButton, cc.xy(1, 3));
        bRadioButton = new JRadioButton();
        bRadioButton.setText("B");
        buttonPanelModule.add(bRadioButton, cc.xy(1, 5));
        cRadioButton = new JRadioButton();
        cRadioButton.setText("C");
        buttonPanelModule.add(cRadioButton, cc.xy(1, 7));
        dRadioButton = new JRadioButton();
        dRadioButton.setText("D");
        buttonPanelModule.add(dRadioButton, cc.xy(1, 9));
        eRadioButton = new JRadioButton();
        eRadioButton.setText("E");
        buttonPanelModule.add(eRadioButton, cc.xy(1, 11));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(aRadioButton);
        buttonGroup.add(bRadioButton);
        buttonGroup.add(cRadioButton);
        buttonGroup.add(dRadioButton);
        buttonGroup.add(eRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public JPanel getRootPanel() {
        return mainPanel;
    }

    public List<AbstractButton> getButtons() {

        return buttons;

    }

    public void refreshButtons() {
        ButtonGroup buttonGroup;
        CellConstraints cc = new CellConstraints();
        buttonGroup = new ButtonGroup();
        buttonPanelModule.removeAll();
        String rowConstraints = "center:d:noGrow,";
        for (int i = 1; i <= buttons.size(); i++) {
            rowConstraints += "top:4dlu:noGrow,";
            rowConstraints += "center:max(d;4px):noGrow,";
        }
        rowConstraints = rowConstraints.substring(0, rowConstraints.length() - 1);
        buttonPanelModule.setLayout(new FormLayout(
                "fill:d:noGrow", rowConstraints));
        buttonPanelModule.add(label, new CellConstraints(1, 1, 1, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(5, 5, 5, 5)));
        for (int i = 3, button = 0; button < buttons.size(); button++, i += 2) {
            buttonPanelModule.add(buttons.get(button), cc.xy(1, i));
            buttonGroup.add(buttons.get(button));
        }
    }
}
