import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class ButtonPanel {
    private JPanel mainPanel;
    private JButton button1;
    private JRadioButton aRadioButton;
    private JRadioButton bRadioButton;
    private JRadioButton cRadioButton;
    private JRadioButton dRadioButton;
    private JRadioButton eRadioButton;
    private JPanel buttonPanelModule;
    StringBuffer input;

    public ButtonPanel(StringBuffer input) {
        this.input = input;
        button1.addActionListener(new ActionListener() {
            /**
             * @param e
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                if (aRadioButton.isSelected()) {
                    input.append(aRadioButton.getText());
                    input.append("\n");
                }
                if (bRadioButton.isSelected()) {
                    input.append(bRadioButton.getText());
                    input.append("\n");
                }
                if (cRadioButton.isSelected()) {
                    input.append(cRadioButton.getText());
                    input.append("\n");
                }
                if (dRadioButton.isSelected()) {
                    input.append(dRadioButton.getText());
                    input.append("\n");
                }
                if (eRadioButton.isSelected()) {
                    input.append(eRadioButton.getText());
                    input.append("\n");
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:179px:noGrow", "center:377px:grow,top:4dlu:noGrow,center:d:grow"));
        mainPanel.setPreferredSize(new Dimension(200, 600));
        button1 = new JButton();
        button1.setPreferredSize(new Dimension(78, 50));
        button1.setText("Button");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(button1, new CellConstraints(1, 3, 1, 1, CellConstraints.DEFAULT, CellConstraints.BOTTOM, new Insets(0, 5, 0, 5)));
        buttonPanelModule = new JPanel();
        buttonPanelModule.setLayout(new FormLayout("fill:d:noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        buttonPanelModule.setPreferredSize(new Dimension(200, 175));
        mainPanel.add(buttonPanelModule, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.TOP));
        final JLabel label1 = new JLabel();
        label1.setAutoscrolls(true);
        label1.setPreferredSize(new Dimension(200, 25));
        label1.setText("Label");
        buttonPanelModule.add(label1, new CellConstraints(1, 1, 1, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(5, 5, 5, 5)));
        aRadioButton = new JRadioButton();
        aRadioButton.setText("A");
        buttonPanelModule.add(aRadioButton, cc.xy(1, 3));
        bRadioButton = new JRadioButton();
        bRadioButton.setText("B");
        buttonPanelModule.add(bRadioButton, cc.xy(1, 5));
        cRadioButton = new JRadioButton();
        cRadioButton.setText("C");
        buttonPanelModule.add(cRadioButton, cc.xy(1, 7));
        dRadioButton = new JRadioButton();
        dRadioButton.setText("D");
        buttonPanelModule.add(dRadioButton, cc.xy(1, 9));
        eRadioButton = new JRadioButton();
        eRadioButton.setText("E");
        buttonPanelModule.add(eRadioButton, cc.xy(1, 11));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(aRadioButton);
        buttonGroup.add(bRadioButton);
        buttonGroup.add(cRadioButton);
        buttonGroup.add(dRadioButton);
        buttonGroup.add(eRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public JPanel getRootPanel() {
        return mainPanel;
    }

    public List<AbstractButton> getButtons() {
        ArrayList<AbstractButton> buttons = new ArrayList<>();
        buttons.add(aRadioButton);
        buttons.add(bRadioButton);
        buttons.add(cRadioButton);
        buttons.add(dRadioButton);
        buttons.add(eRadioButton);

        return buttons;

    }
}
