import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class InputPanel {
    private JPanel mainPanel;
    private JButton button1;
    private JRadioButton aRadioButton;
    private JRadioButton bRadioButton;
    private JRadioButton cRadioButton;
    private JRadioButton dRadioButton;
    private JRadioButton eRadioButton;
    private JPanel inputPanelModule;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:179px:noGrow", "center:377px:grow,top:4dlu:noGrow,center:d:grow"));
        mainPanel.setPreferredSize(new Dimension(200, 600));
        button1 = new JButton();
        button1.setPreferredSize(new Dimension(78, 50));
        button1.setText("Button");
        CellConstraints cc = new CellConstraints();
        mainPanel.add(button1, new CellConstraints(1, 3, 1, 1, CellConstraints.DEFAULT, CellConstraints.BOTTOM, new Insets(0, 5, 0, 5)));
        inputPanelModule = new JPanel();
        inputPanelModule.setLayout(new FormLayout("fill:d:noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        inputPanelModule.setPreferredSize(new Dimension(200, 175));
        mainPanel.add(inputPanelModule, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.TOP));
        final JLabel label1 = new JLabel();
        label1.setAutoscrolls(true);
        label1.setPreferredSize(new Dimension(200, 25));
        label1.setText("Label");
        inputPanelModule.add(label1, new CellConstraints(1, 1, 1, 1, CellConstraints.FILL, CellConstraints.DEFAULT, new Insets(5, 5, 5, 5)));
        aRadioButton = new JRadioButton();
        aRadioButton.setText("A");
        inputPanelModule.add(aRadioButton, cc.xy(1, 3));
        bRadioButton = new JRadioButton();
        bRadioButton.setText("B");
        inputPanelModule.add(bRadioButton, cc.xy(1, 5));
        cRadioButton = new JRadioButton();
        cRadioButton.setText("C");
        inputPanelModule.add(cRadioButton, cc.xy(1, 7));
        dRadioButton = new JRadioButton();
        dRadioButton.setText("D");
        inputPanelModule.add(dRadioButton, cc.xy(1, 9));
        eRadioButton = new JRadioButton();
        eRadioButton.setText("E");
        inputPanelModule.add(eRadioButton, cc.xy(1, 11));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public JPanel getRootPanel() {
        return mainPanel;
    }
}
