import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.io.InputStream;
import java.io.PrintStream;

public class TextGUI {
    private JPanel mainPanel;
    private InputPanel inputPanel;
    private ConsolePanel consolePanel;
    private JPanel consolePanelRootPanel;
    private JPanel inputPanelRootPanel;
    public final PrintStream out;
    public final InputStream in;

    private CellConstraints defaultInputPanelConstraints;


    public TextGUI(String title) {
        JFrame mainFrame = new JFrame(title);
        consolePanel = new ConsolePanel();
        inputPanel = new InputPanel();
        $$$setupUI$$$();
        mainFrame.setContentPane(mainPanel);
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainFrame.pack();
        mainFrame.setVisible(true);
        out = consolePanel.out;
        in = consolePanel.in;
        defaultInputPanelConstraints = ((FormLayout) mainPanel.getLayout()).getConstraints(inputPanelRootPanel);
        this.hideInputPanel();
    }

    public TextGUI() {
        this("TextGUI");
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:259px:grow(1.1)"));
        mainPanel.setPreferredSize(new Dimension(800, 600));
        inputPanelRootPanel.setPreferredSize(new Dimension(200, 600));
        CellConstraints cc = new CellConstraints();
        mainPanel.add(inputPanelRootPanel, new CellConstraints(1, 1, 1, 1, CellConstraints.DEFAULT, CellConstraints.DEFAULT, new Insets(10, 10, 10, 10)));
        consolePanelRootPanel.setPreferredSize(new Dimension(800, 600));
        mainPanel.add(consolePanelRootPanel, cc.xy(3, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        consolePanelRootPanel = consolePanel.getRootPanel();
        inputPanelRootPanel = inputPanel.getRootPanel();
    }

    public void clear() {
        consolePanel.clear();
    }

    public void hideInputPanel() {
        defaultInputPanelConstraints = ((FormLayout) mainPanel.getLayout()).getConstraints(inputPanelRootPanel);
        mainPanel.remove(inputPanelRootPanel);
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    public void showInputPanel() {
        mainPanel.add(inputPanelRootPanel, defaultInputPanelConstraints, 0);
        mainPanel.revalidate();
        mainPanel.repaint();
    }
}
